# Generated by Django 5.2.1 on 2025-06-18 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sem titulo fornecido', max_length=200, verbose_name='Titulo')),
                ('tipo_de_evento', models.CharField(choices=[('Prova', 'Prova'), ('Atividade', 'Atividade'), ('Tarefa', 'Tarefa'), ('Importante.', 'Importante'), ('Lembrete', 'Lembrete'), ('Passeio', 'Passeio'), ('Outro', 'Outro')], max_length=18)),
                ('descricao', models.CharField(default='Sem descrição', max_length=200, verbose_name='Detalhe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('dia_do_evento', models.DateTimeField(verbose_name='Data do evento')),
                ('importancia', models.CharField(choices=[('Mínima', '1'), ('Mediana', '2'), ('Máxima', '3')], default=('Mínima', '1'), verbose_name='Importância')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(choices=[('blue', 'blue'), ('green', 'green'), ('red', 'red'), ('white', 'white')], default='blue', max_length=10, verbose_name='Cor de destaque')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
