# Generated by Django 5.2.1 on 2025-06-18 20:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['dia_do_evento']},
        ),
        migrations.RemoveField(
            model_name='colors',
            name='id',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='dia_do_evento',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do evento'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='importancia',
            field=models.CharField(choices=[('1', 'Mínima'), ('2', 'Mediana'), ('3', 'Máxima')], default='1', max_length=2, verbose_name='Importância'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='tipo_de_evento',
            field=models.CharField(choices=[('Prova', 'Prova'), ('Atividade', 'Atividade'), ('Tarefa', 'Tarefa'), ('Importante', 'Importante'), ('Lembrete', 'Lembrete'), ('Passeio', 'Passeio'), ('Outro', 'Outro')], default='Lembrete', max_length=20, verbose_name='Tipo de Evento'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='colors',
            name='cor',
            field=models.CharField(choices=[('blue', 'Azul'), ('green', 'Verde'), ('red', 'Vermelho'), ('white', 'Branco')], default='blue', max_length=10, verbose_name='Cor de destaque'),
        ),
        migrations.AlterField(
            model_name='colors',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
