# Generated by Django 5.2.1 on 2025-10-26 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('init', '0011_alter_todo_prazo_final_alter_todo_prazo_inicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Tarefa')),
                ('feito', models.BooleanField(default=False)),
                ('color', models.CharField(choices=[('red', 'Vermelho'), ('green', 'Verde'), ('blue', 'Azul'), ('yellow', 'Amarelo'), ('orange', 'Laranja'), ('purple', 'Roxo'), ('black', 'Preto'), ('white', 'Branco')], default=('black', 'black'))),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='init.todo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('red', 'Vermelho'), ('green', 'Verde'), ('blue', 'Azul'), ('yellow', 'Amarelo'), ('orange', 'Laranja'), ('purple', 'Roxo'), ('black', 'Preto'), ('white', 'Branco')], default=('black', 'black'))),
                ('itens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.itens')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
