# Generated by Django 5.2.1 on 2025-10-26 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulo',
            name='itens',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='checklist.itens'),
        ),
    ]
