# Generated by Django 5.2.1 on 2025-10-26 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_alter_titulo_itens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itens',
            name='task',
        ),
        migrations.RemoveField(
            model_name='titulo',
            name='itens',
        ),
        migrations.AddField(
            model_name='itens',
            name='titulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='checklist.titulo'),
        ),
        migrations.AlterField(
            model_name='itens',
            name='color',
            field=models.CharField(choices=[('red', 'Vermelho'), ('green', 'Verde'), ('blue', 'Azul'), ('yellow', 'Amarelo'), ('orange', 'Laranja'), ('purple', 'Roxo'), ('black', 'Preto'), ('white', 'Branco')], default='black', max_length=20),
        ),
        migrations.AlterField(
            model_name='itens',
            name='label',
            field=models.CharField(default='Tarefa', max_length=255),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='color',
            field=models.CharField(choices=[('red', 'Vermelho'), ('green', 'Verde'), ('blue', 'Azul'), ('yellow', 'Amarelo'), ('orange', 'Laranja'), ('purple', 'Roxo'), ('black', 'Preto'), ('white', 'Branco')], default='black', max_length=20),
        ),
    ]
