# Generated by Django 5.2.1 on 2025-05-31 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('anotacao', models.CharField(max_length=3000)),
                ('prioridade', models.CharField(choices=[('UM', '1'), ('DOIS', '2'), ('TRES', '3'), ('QUATRO', '4'), ('CINCO', '5')], max_length=10)),
                ('data_de_criacao', models.DateField(auto_now_add=True)),
                ('tag', models.CharField(choices=[('Esc.', 'Universidade'), ('Any', 'Outro'), ('Casa', 'Casa'), ('Urg.', 'Urgente'), ('Imp.', 'Importante'), ('Rot.', 'Rotina'), ('Tar.', 'Tarefa'), ('Lem.', 'Lembrete')], max_length=10)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
