# Generated by Django 5.2.1 on 2025-06-04 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('anotacao', models.CharField(max_length=50000)),
                ('prioridade', models.CharField(choices=[('Mínima', '1'), ('Mediana', '2'), ('Máxima', '3')], max_length=10)),
                ('data_de_criacao', models.DateField(auto_now_add=True)),
                ('prazo_inicial', models.DateField()),
                ('prazo_final', models.DateField()),
                ('tag', models.CharField(choices=[('Universidade.', 'Universidade'), ('Casa', 'Casa'), ('Urgente.', 'Urgente'), ('Importante.', 'Importante'), ('Rotina.', 'Rotina'), ('Tarefa.', 'Tarefa'), ('Lembrete.', 'Lembrete'), ('Outro', 'Outro')], max_length=13)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
