# Generated by Django 5.2.1 on 2025-06-01 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='id_user',
            new_name='user',
        ),
    ]
