# Generated by Django 5.2.1 on 2025-06-07 09:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0002_alter_todo_prazo_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='prazo_inicial',
            field=models.DateField(default=django.utils.timezone.now, help_text='eg. 2025-06-07'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='tag',
            field=models.CharField(choices=[('Universidade.', 'Universidade'), ('Casa', 'Casa'), ('Urgente.', 'Urgente'), ('Importante.', 'Importante'), ('Tarefa.', 'Tarefa'), ('Lembrete.', 'Lembrete'), ('Outro', 'Outro')], max_length=13),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Image')),
                ('descricao', models.CharField(default='Imagem sem descriçao', max_length=1000)),
                ('titulo', models.CharField(default='Sem titulo', max_length=1000)),
                ('data_de_criacao', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagem', to='init.todo')),
            ],
        ),
    ]
