# Generated by Django 5.2.1 on 2025-06-18 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0002_remove_todo_data_de_criacao_todo_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='data_de_criacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
