# Generated by Django 5.2.1 on 2025-06-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0002_rename_id_user_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='prioridade',
            field=models.CharField(choices=[('Mínima', '1'), ('Mediana', '2'), ('Máxima', '3')], max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='tag',
            field=models.CharField(choices=[('Esc.', 'Universidade'), ('Casa', 'Casa'), ('Urg.', 'Urgente'), ('Imp.', 'Importante'), ('Rot.', 'Rotina'), ('Tar.', 'Tarefa'), ('Lem.', 'Lembrete'), ('Any', 'Outro')], max_length=10),
        ),
    ]
