# Generated by Django 5.2.1 on 2025-06-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0003_alter_todo_prazo_inicial_alter_todo_tag_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='imgs'),
        ),
    ]
