# Generated by Django 5.2.1 on 2025-06-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0004_alter_image_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='observacao',
            field=models.CharField(default='Sem observação', max_length=300),
        ),
    ]
