# Generated by Django 5.2.1 on 2025-06-08 01:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0006_alter_image_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='prazo_inicial',
            field=models.DateField(default=django.utils.timezone.now, help_text='eg. 2025-06-08'),
        ),
    ]
