# Generated by Django 5.2.1 on 2025-10-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
