# Generated by Django 5.2.1 on 2025-06-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='importancia',
            field=models.CharField(choices=[('1', 'Mínima'), ('2', 'Mediana'), ('3', 'Máxima')], default=('1', 'Mínima'), max_length=2, verbose_name='Importância'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='tipo_de_evento',
            field=models.CharField(choices=[('Prova', 'Prova'), ('Atividade', 'Atividade'), ('Terefa', 'Tarefa'), ('Importante', 'Importante'), ('Lembrete', 'Lembrete'), ('Outro', 'Outro')], default=('Lembrete', 'Lembrete'), max_length=20, verbose_name='Tipo de Evento'),
        ),
    ]
