# Generated by Django 5.2.1 on 2025-06-19 12:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_agenda_importancia_alter_agenda_tipo_de_evento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agenda',
            new_name='AgendaModel',
        ),
    ]
