# Generated by Django 5.2.1 on 2025-06-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_rename_agenda_agendamodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colors',
            old_name='cor',
            new_name='cor_de_destaque',
        ),
        migrations.AddField(
            model_name='colors',
            name='cor_do_dia',
            field=models.CharField(choices=[('blue', 'Azul'), ('green', 'Verde'), ('red', 'Vermelho'), ('white', 'Branco')], default='blue', max_length=10, verbose_name='Cor de destaque'),
        ),
    ]
