# Generated by Django 5.2.1 on 2025-06-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_rename_cor_colors_cor_de_destaque_colors_cor_do_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamodel',
            name='descricao',
            field=models.TextField(blank=True, default='Sem descrição', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='agendamodel',
            name='titulo',
            field=models.CharField(default='Sem titulo', max_length=200, verbose_name='Título'),
        ),
    ]
