# Generated by Django 5.2.1 on 2025-06-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_agendamodel_descricao_alter_agendamodel_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='cor_de_destaque',
            field=models.CharField(choices=[('blue', 'Azul'), ('green', 'Verde'), ('red', 'Vermelho'), ('white', 'Branco'), ('rgb(255, 165, 0)', 'Laranja')], default='blue', max_length=19, verbose_name='Cor de destaque'),
        ),
        migrations.AlterField(
            model_name='colors',
            name='cor_do_dia',
            field=models.CharField(choices=[('blue', 'Azul'), ('green', 'Verde'), ('red', 'Vermelho'), ('white', 'Branco'), ('rgb(255, 165, 0)', 'Laranja')], default='blue', max_length=19, verbose_name='Cor de destaque'),
        ),
    ]
