# Generated by Django 5.2.1 on 2025-06-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_colors_cor_de_destaque_alter_colors_cor_do_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='cor_de_destaque',
            field=models.CharField(choices=[('blue', 'Azul'), ('green', 'Verde'), ('red', 'Vermelho'), ('black', 'Preto'), ('#FFFFFF', 'Branco'), ('#FFC107', 'Amarelo'), ('orange', 'Laranja'), ('#6f42c1', 'Roxo'), ('#d63384', 'Rosa'), ('#0dcaf0', 'Ciano/Turquesa'), ('#6c757d', 'Cinza'), ('#795548', 'Marrom'), ('#FFD700', 'Dourado'), ('#C0C0C0', 'Prata')], default='blue', max_length=19, verbose_name='Cor de destaque'),
        ),
        migrations.AlterField(
            model_name='colors',
            name='cor_do_dia',
            field=models.CharField(choices=[('blue', 'Azul'), ('green', 'Verde'), ('red', 'Vermelho'), ('black', 'Preto'), ('#FFFFFF', 'Branco'), ('#FFC107', 'Amarelo'), ('orange', 'Laranja'), ('#6f42c1', 'Roxo'), ('#d63384', 'Rosa'), ('#0dcaf0', 'Ciano/Turquesa'), ('#6c757d', 'Cinza'), ('#795548', 'Marrom'), ('#FFD700', 'Dourado'), ('#C0C0C0', 'Prata')], default='blue', max_length=19, verbose_name='Cor de destaque'),
        ),
    ]
