# Generated by Django 5.2.1 on 2025-06-21 13:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('favorito', models.BooleanField(default=False)),
                ('completo', models.BooleanField(default=False)),
                ('anotacao', models.TextField(default='Escreva algo aqui!', verbose_name='Anotação')),
                ('prioridade', models.CharField(choices=[('Mínima', '1'), ('Mediana', '2'), ('Máxima', '3')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('tag', models.CharField(choices=[('Universidade.', 'Universidade'), ('Casa', 'Casa'), ('Urgente.', 'Urgente'), ('Importante.', 'Importante'), ('Tarefa.', 'Tarefa'), ('Lembrete.', 'Lembrete'), ('Outro', 'Outro')], max_length=13)),
                ('prazo_inicial', models.DateField(default=django.utils.timezone.now, help_text='eg. 2025-06-21')),
                ('prazo_final', models.DateField(default=django.utils.timezone.now, help_text='eg. 2025-06-21')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='imgs')),
                ('descricao', models.CharField(default='Imagem sem descriçao', max_length=1000)),
                ('titulo', models.CharField(default='Sem titulo', max_length=1000)),
                ('data_de_criacao', models.DateField(default=django.utils.timezone.now)),
                ('observacao', models.CharField(default='Sem observação', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagem', to='init.todo')),
            ],
        ),
    ]
