# Generated by Django 5.2.1 on 2025-06-20 21:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='prazo_final',
            field=models.DateField(default=django.utils.timezone.now, help_text='eg. 2025-06-20'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='prazo_inicial',
            field=models.DateField(default=django.utils.timezone.now, help_text='eg. 2025-06-20'),
        ),
    ]
