# Generated by Django 5.2.1 on 2025-10-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0007_alter_todo_prazo_final_alter_todo_prazo_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='prioridade',
            field=models.CharField(choices=[('Mínima', '1'), ('Mediana', '2'), ('Máxima', '3')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='tag',
            field=models.CharField(choices=[('Universidade.', 'Universidade'), ('Casa', 'Casa'), ('Urgente.', 'Urgente'), ('Importante.', 'Importante'), ('Tarefa.', 'Tarefa'), ('Lembrete.', 'Lembrete'), ('Avulso', 'Avulso'), ('Outro', 'Outro')], default=('Avulso', 'Avulso'), max_length=13),
        ),
        migrations.AlterField(
            model_name='todo',
            name='titulo',
            field=models.CharField(default='Sem titulo', max_length=200),
        ),
    ]
