# Generated by Django 5.2.1 on 2025-10-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0008_alter_todo_prioridade_alter_todo_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
